//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie1
{
    using System.Collections.Generic;
    
    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.Product_Sale = new HashSet<Product_Sale>();
        }
    
        public int ID_Agent { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string logo { get; set; }
        public string adress { get; set; }
        public int priority { get; set; }
        public string director { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public int ID_Type_Agents { get; set; }
    
        public virtual Type_Agents Type_Agents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Sale> Product_Sale { get; set; }

    }
}
